name: my-first-workflow
# To get trigger on every push in this repo in any branch
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in JOB1
        run: echo "Hi this is first Githubworkflow"
      - name: checking the OS Release for Github action
        run: cat /etc/os-release
